# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
- task: SonarScanner@1
  inputs:
    endpoint: 'SonarQube'
    sonarServer: 'http://40.76.138.192:9000'
    version: '4.8.0.2856'
    configMode: 'manual'
    projectKey: 'TEST'
    projectName: 'TEST'
    projectVersion: '1.0'
    branchName: 'main'
    sources: '*'
    extraProperties: |
      # Write your additional sonar-scanner properties here.
      
      sonar.exclusions=**\tests
    debug: true
