# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Aks-Build-agents

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube-2'
    scannerMode: 'cli'
    cliScannerVersion: '7.1.0.4889'
    configMode: 'manual'
    cliProjectKey: 'test-proj'
    cliProjectName: 'test-proj'
    cliSources: '.'
