trigger:
- main

stages:
- stage: build

  pool:
   name: Aks-Build-agents
  
  jobs:
  - job: buildApp
    strategy:
          matrix:
            build01:
              myVar: '1.0'
            build02:
              myVar: '1.0'

  - job: buildApp02
    steps:
    - script: |
        echo "Hello from inside Docker Container: $HOSTNAME"
        printenv